### ISSUE TITLE
Hangs Chrome

### ISSUE THREAD

**Issue by cozzbie** [klughammer/node-randomstring#27]
For some reason this hangs Chrome indefinitely. Anyone else experiencing this?

**Comment by AndrewEckart** [comment]
I was using this library previously without issues, but now it's hanging Chrome for me as well.

Chrome version: 63.0.3239.132
Randomstring version: 1.1.5

It's a shame because the options are great and it was perfect for what I needed. Since this seems unmaintained I'll probably have to find a different lib or create my own implementation.

**Comment by CezaryDanielNowak** [comment]
For me this issue happens when using window.crypto instead of heavy (300KB) polyfill version from webpack.

**Comment by eliaskg** [comment]
Thank you! Should be fixed via the latest version.
